name: definitely_not_window
description: Flutter extension enabling you to create custom window bar on desktop and manage window position, size and state via Dart.

version: 0.1.0+1

environment:
  sdk: ">=2.17.0-271.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  win32: ^2.7.0
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: DefinitelyNotWindowPlugin
